proc import
datafile='C:\Users\gabriele.politi2\Desktop\ClamdaIM\datas.xlsx'
dbms=xlsx
out=project;
getnames=yes;
run;

libname rest 'C:\Users\gabriele.politi2\Desktop\ClamdaIM\';
data rest.questionario;
set project;
obs_id=_n_;
run;

proc datasets lib=rest;
modify questionario;
label SC1='Use';
label SC2='Average';
label SC3='Reason';
label SC4_1='Use_Smartphone';
label SC4_2='Use_PC';
label SC4_3='Use_Tablet';
label SC4_4='Use_SmartTv';
label SC4_5='Use_GameConsole';
label SC5_1='Why_PersonalSearch';
label SC5_2='Why_SocialMedia';
label SC5_3='Why_ProfessionalResearch';
label SC5_4='Why_SpecialTools';
label SC5_5='Why_VideoandStreamingServices';
label SC5_6='Why_Interaction';
label SC5_7='Why_Learning';
label SC5_8='Why_AI';
label SC5_9='Why_Buying';
label SC5_10='Other';
label SC6='Web_Browsers';
label SC7='Preinstalled';
label A1='imp_Privacy';
label A2='imp_Security';
label A3='imp_Feature';
label A4='imp_Search';
label A5='imp_Interface';
label A6='imp_Customization';
label A7='imp_Integration';
label A8='imp_MobileInterface';
label A9='imp_Speed';
label ST='Overall_Satisfaction';
label SD1='Gender';
label SD2='Age';
label SD3='Countries';
label SD4='Occupation';
label SD5='Degree';
run;
proc freq data=rest.questionario;
table SD1--SD5;
run;
proc means data=rest.questionario;
var A1-A9;
run;
proc princomp data=rest.questionario;
var A1-A9;
run;
proc princomp data=rest.questionario
out=rest.data_coord;
var A1-A9;
run;
proc corr data=rest.data_coord;
var prin1-prin9;
run;
data rest.data_coord_1;set rest.data_coord;
avg_i=.;
avg_i=mean(of A1-A9);
run;
proc corr data=rest.data_coord_1;
var avg_i prin1;
run;
data rest.data_adj; set rest.questionario;
avg_i=mean(of A1-A9);
min_i=min(of A1-A9);
max_i=max(of A1-A9);
array a A1-A9;
array b new1-new9;
do over b;
b=.;
if a>avg_i then b=(a-avg_i)/(max_i-avg_i);
if a<avg_i then b=(a-avg_i)/(avg_i-min_i);
if a=avg_i then b=0;
if a=. then b=0;
end;
label new1='privacy';
label new2='security';
label new3='feature';
label new4='search';
label new5='interface';
label new6='customization';
label new7='integration';
label new8='mobileinterface';
label new9='speed';
run;
 /*FINAL PCA*/
proc princomp data=rest.data_adj
out=rest.data_coord_1_adj;
var new1-new9;
run;
 /*CLUSTERING*/
proc cluster data=rest.data_coord_1_adj method=ward outtree=rest.data_tree;
var prin1-prin4;
id obs_id;
run;
proc template;
define statgraph dendrogram;
begingraph;
layout overlay;
dendrogram nodeID=_name parentID=_parent_ clusterheight=_height_;
endlayout;
endgraph;
end;
run;
proc sgrender data=rest.data_tree template=dendogram;
run;
proc tree data=rest.data_tree ncl=5 out=rest.data_cluster;
id obs_id;
run;
 /*PRELIMINARY OPERATIONS*/
proc sort data=rest.data_coord_1_adj;
by obs_id;
run;
proc sort data=rest.data_cluster;
by obs_id;
run;
data rest.data_merged;
merge rest.data_coord_1_adj rest.data_cluster;
by obs_id;
run;
data rest.data_fake;
set rest.data_merged;
cluster=5;
run;
data rest.data_appendend;
set rest.data_merged rest.data_fake;
run;
/*T-TEST*/
proc ttest data=rest.data_appendend;
var new:;
class cluster;
where cluster=1 or cluster=5;
run;
proc ttest data=rest.data_appendend;
var new:;
class cluster;
where cluster=2 or cluster=5;
run;
proc ttest data=rest.data_appendend;
var new:;
class cluster;
where cluster=3 or cluster=5;
run;
proc ttest data=rest.data_appendend;
var new:;
class cluster;
where cluster=4 or cluster=5;
run;
/*CHI SQUARE*/
proc freq data=rest.data_merged;
table SD1*cluster/expected chisq;
run;
proc freq data=rest.data_merged;
table SD2*cluster/expected chisq;
run;
proc freq data=rest.data_merged;
table SD3*cluster/expected chisq;
run;
proc freq data=rest.data_merged;
table SD4*cluster/expected chisq;
run;
proc freq data=rest.data_merged;
table SD5*cluster/expected chisq;
run;
